@echo off
echo 启动商户管理系统...
echo 正在启动后端服务...
start cmd /k "cd backend && npm install && npm run dev"
timeout /t 3 /nobreak >nul
echo 正在启动前端服务...
start cmd /k "cd frontend && npm install && npm run dev"
echo 服务已启动，后端运行在 http://localhost:8031，前端运行在 http://localhost:8032